import os
import requests
from google.colab import userdata

SYSTEM_PROMPT = """
You are Khana21, a source-grounded Jyotisha interpretation system.

You are given:
1. Computational chart data generated by Parashar21.
2. Access to an authorised Jyotisha reference corpus through file search.

RULES:

- Treat the Parashar21 chart data as factual case data.
- Base all Jyotisha interpretation ONLY on the authorised reference corpus
  retrieved through file search.
- Do NOT use astrological knowledge from your pretrained knowledge.
- Do NOT invent rules, yogas, significations, aspects, lordships or
  interpretations that are not supported by the supplied corpus.
- Treat the user's question as a hypothesis to examine, not a premise
  to confirm.
- Search for evidence both supporting and contradicting the hypothesis
  where such evidence exists.
- Give greater weight to specific rules matching the chart configuration
  than to broad planetary, sign or house significations.
- When specific and general rules conflict, explicitly identify the
  conflict and give priority to the more specific applicable rule.
- If the supplied corpus provides insufficient evidence, say so clearly.
- Identify the source used for important conclusions.
"""


try:
    # Load key from Colab Secrets into environment
    api_key = userdata.get("OPENAI_API_KEY")
    if not api_key:
        raise ValueError("OPENAI_API_KEY not found in Colab Secrets")

    os.environ["OPENAI_API_KEY"] = api_key
    print("API key loaded ✔")

    # Call OpenAI identity endpoint
    headers = {
        "Authorization": f"Bearer {api_key}"
    }

    resp = requests.get("https://api.openai.com/v1/me", headers=headers)
    resp.raise_for_status()   # catches 401 / 403 / etc.

    me = resp.json()
    name = me.get("name", "N/A")
    email = me.get("email", "N/A")

    print(f"Logged in as {name} {email}")

except Exception as e:
    print("❌ OpenAI credential check failed")
    print("Reason:", str(e))


def read_txt(path):
    with open(path, "r", encoding="utf-8") as f:
        return f.read()


def CreateVectorStore(client,_name,corpus1, corpus2):
    from openai import OpenAI

    #client = OpenAI()

    # Create our permanent Khawna knowledge base
    vector_store = client.vector_stores.create(name=_name)

    VECTOR_STORE_ID = vector_store.id

    print("Vector Store:", VECTOR_STORE_ID)

    # Upload Braha and Harihar
    with open(corpus1, "rb") as f1, \
         open(corpus2, "rb") as f2:

        result = client.vector_stores.file_batches.upload_and_poll(
            vector_store_id = VECTOR_STORE_ID,
            files=[f1, f2]
        )

    print(result)
    return(VECTOR_STORE_ID)
    
def TestRetrieval(client, vsID, cquery):
    # Pure retrieval test — NO LLM

    results = client.vector_stores.search(
        #vector_store_id="vs_6ab4bd1cfbe081919a3876771cfd3271",
        vector_store_id = vsID,
        query=cquery
    )

    for i, item in enumerate(results.data, 1):
        print(f"\n{'='*70}")
        print(f"RESULT {i}")
        print(f"File:  {item.filename}")
        print(f"Score: {item.score:.4f}")

        for content in item.content:
            if content.type == "text":
                print(content.text)
                
def buildCaseContext(_chart, _navamsa, _dasha):
    CASE_CONTEXT = f"""
    ====================
    RASHI / NATAL CHART
    ====================
    {_chart}

    ====================
    NAVAMSA
    ====================
    {_navamsa}

    ====================
    VIMSHOTTARI DASHA
    ====================
    {_dasha}
    """
    return(CASE_CONTEXT)
                
def LLM_Response(client,systemPrompt, caseContext, cQuestion, vsID) :
    # Call to LLM
    response = client.responses.create(
    model="gpt-5.6-luna",
    instructions=systemPrompt,
    input=f"""
    {caseContext}

    ====================
    QUESTION
    ====================
    {cQuestion}
    """,

        tools=[
            {
                "type": "file_search",
                "vector_store_ids": [vsID]
            }
        ]
    )
    return(response)
    
# ------------Cleanup -----------------------------------------------

def showVectorStores(client):
    stores = client.vector_stores.list()

    for store in stores.data:
            print(store.id, store.name)
            
def deleteVectorStores(client):
    stores = client.vector_stores.list()

    for store in stores.data:
        print(store.id, store.name)
        client.vector_stores.delete(vector_store_id=store.id)
        
def showCorpusFiles(client):
    files = client.files.list()

    for f in files.data:
        print(f.id, f.filename)
        
def deleteCorpusFiles(client):
    files = client.files.list()

    for f in files.data:
        print(f.id, f.filename)
        client.files.delete(f.id)

    print("Corpus files deleted")
        



