import os
import requests
from google.colab import userdata

from IPython.display import display, Markdown

#------------------------------------------------------------------------------------------

SYSTEM_PROMPT = """
You are Khana21, a source-grounded Jyotisha interpretation system.

You are given:
1. Computational chart data generated by Parashar21.
2. Access to an authorised Jyotisha reference corpus through file search.

RULES:

- Treat the Parashar21 chart data as factual case data.
- Base all Jyotisha interpretation ONLY on the authorised reference corpus
  retrieved through file search.
- Do NOT use astrological knowledge from your pretrained knowledge.
- Do NOT invent rules, yogas, significations, aspects, lordships or
  interpretations that are not supported by the supplied corpus.
- Treat the user's question as a hypothesis to examine, not a premise
  to confirm.
- Search for evidence both supporting and contradicting the hypothesis
  where such evidence exists.
- Give greater weight to specific rules matching the chart configuration
  than to broad planetary, sign or house significations.
- When specific and general rules conflict, explicitly identify the
  conflict and give priority to the more specific applicable rule.
- If the supplied corpus provides insufficient evidence, say so clearly.
- Identify the source used for important conclusions.
"""

#------------------------------------------------------------------------------------------

def authenticateOpenAI():

    import os
    import requests
    from google.colab import userdata
    from openai import OpenAI

    try:
        # Get key from Colab Secrets
        api_key = userdata.get("OPENAI_API_KEY")

        if not api_key:
            raise ValueError(
                "OPENAI_API_KEY not found in Colab Secrets"
            )

        os.environ["OPENAI_API_KEY"] = api_key

        # Check identity
        headers = {
            "Authorization": f"Bearer {api_key}"
        }

        resp = requests.get(
            "https://api.openai.com/v1/me",
            headers=headers
        )

        resp.raise_for_status()

        me = resp.json()

        name = me.get("name", "N/A")
        email = me.get("email", "N/A")

        print("OpenAI authentication successful ✔")
        print(f"Logged in as {name} {email}")

        # Create and return authenticated client
        return OpenAI(api_key=api_key)

    except Exception as e:

        print("❌ OpenAI credential check failed")
        print("Reason:", str(e))

        return None

#------------------------------------------------------------------------------------------

def read_txt(path):
    with open(path, "r", encoding="utf-8") as f:
        return f.read()


#STORE_NAME = "Khana21"

def getVectorStore(client, store_name="Khana21"):

    matches = [
        store for store in client.vector_stores.list().data
        if store.name == store_name
    ]

    if not matches:
        print(f"Vector store '{store_name}' not found")
        return None

    if len(matches) > 1:
        print(
            f"WARNING: {len(matches)} vector stores named "
            f"'{store_name}' found. Using the first."
        )

    return matches[0].id

#------------------------------------------------------------------------------------------

def createVectorStore(client,_name,corpus1, corpus2):
    from openai import OpenAI

    #client = OpenAI()

    # Create our permanent Khawna knowledge base
    vector_store = client.vector_stores.create(name=_name)

    VECTOR_STORE_ID = vector_store.id

    print("Vector Store:", VECTOR_STORE_ID)

    # Upload Braha and Harihar
    with open(corpus1, "rb") as f1, \
         open(corpus2, "rb") as f2:

        result = client.vector_stores.file_batches.upload_and_poll(
            vector_store_id = VECTOR_STORE_ID,
            files=[f1, f2]
        )

    print(result)
    return(VECTOR_STORE_ID)
    
#------------------------------------------------------------------------------------------
    
def TestRetrieval(client, vsID, cquery):
    # Pure retrieval test — NO LLM

    results = client.vector_stores.search(
        #vector_store_id="vs_6ab4bd1cfbe081919a3876771cfd3271",
        vector_store_id = vsID,
        query=cquery
    )

    for i, item in enumerate(results.data, 1):
        print(f"\n{'='*70}")
        print(f"RESULT {i}")
        print(f"File:  {item.filename}")
        print(f"Score: {item.score:.4f}")

        for content in item.content:
            if content.type == "text":
                print(content.text)
                
#------------------------------------------------------------------------------------------

def buildCaseContext(_chart, _navamsa, _dasha):
    CASE_CONTEXT = f"""
    ====================
    RASHI / NATAL CHART
    ====================
    {_chart}

    ====================
    NAVAMSA
    ====================
    {_navamsa}

    ====================
    VIMSHOTTARI DASHA
    ====================
    {_dasha}
    """
    return(CASE_CONTEXT)

#------------------------------------------------------------------------------------------
                
def LLM_Response(client,systemPrompt, caseContext, cQuestion, vsID,_model) :
    # Call to LLM
    response = client.responses.create(
    model=_model,
    instructions=systemPrompt,
    input=f"""
    {caseContext}

    ====================
    QUESTION
    ====================
    {cQuestion}
    """,

        tools=[
            {
                "type": "file_search",
                "vector_store_ids": [vsID]
            }
        ]
    )
    return(response)
    
#------------------------------------------------------------------------------------------

def prettierPrint(response):

    display(Markdown(response.output_text))

    usage = response.usage

    print("-" * 80)
    print(
        f"Tokens: "
        f"input={usage.input_tokens:,} | "
        f"output={usage.output_tokens:,} | "
        f"total={usage.total_tokens:,}"
    )
    print("-" * 80)
    
#------------------------------------------------------------------------------------------

def showVectorStores(client):
    stores = client.vector_stores.list()

    for store in stores.data:
            print(store.id, store.name)
            
def deleteVectorStores(client):
    stores = client.vector_stores.list()

    for store in stores.data:
        print(store.id, store.name)
        client.vector_stores.delete(vector_store_id=store.id)
        
def showCorpusFiles(client):
    files = client.files.list()

    for f in files.data:
        print(f.id, f.filename)
        
def deleteCorpusFiles(client):
    files = client.files.list()

    for f in files.data:
        print(f.id, f.filename)
        client.files.delete(f.id)

    print("Corpus files deleted")
        



