import os
import requests
from google.colab import userdata

from IPython.display import display, Markdown

#------------------------------------------------------------------------------------------

SYSTEM_PROMPT = """
You are Khana21, a source-grounded Jyotisha interpretation system.

You are given:
1. Computational chart data generated by Parashar21.
2. Access to an authorised Jyotisha reference corpus through file search.

RULES:

- Treat the Parashar21 chart data as factual case data.
- Base all Jyotisha interpretation ONLY on the authorised reference corpus
  retrieved through file search.
- Do NOT use astrological knowledge from your pretrained knowledge.
- Do NOT invent rules, yogas, significations, aspects, lordships or
  interpretations that are not supported by the supplied corpus.
- Treat the user's question as a hypothesis to examine, not a premise
  to confirm.
- Search for evidence both supporting and contradicting the hypothesis
  where such evidence exists.
- Give greater weight to specific rules matching the chart configuration
  than to broad planetary, sign or house significations.
- When specific and general rules conflict, explicitly identify the
  conflict and give priority to the more specific applicable rule.
- If the supplied corpus provides insufficient evidence, say so clearly.
- Identify the source used for important conclusions.
"""

#------------------------------------------------------------------------------------------

def authenticateOpenAI():

    import os
    import requests
    from google.colab import userdata
    from openai import OpenAI

    try:
        # Get key from Colab Secrets
        api_key = userdata.get("OPENAI_API_KEY")

        if not api_key:
            raise ValueError(
                "OPENAI_API_KEY not found in Colab Secrets"
            )

        os.environ["OPENAI_API_KEY"] = api_key

        # Check identity
        headers = {
            "Authorization": f"Bearer {api_key}"
        }

        resp = requests.get(
            "https://api.openai.com/v1/me",
            headers=headers
        )

        resp.raise_for_status()

        me = resp.json()

        name = me.get("name", "N/A")
        email = me.get("email", "N/A")

        print("OpenAI authentication successful ✔")
        print(f"Logged in as {name} {email}")

        # Create and return authenticated client
        return OpenAI(api_key=api_key)

    except Exception as e:

        print("❌ OpenAI credential check failed")
        print("Reason:", str(e))

        return None

#------------------------------------------------------------------------------------------

def read_txt(path):
    with open(path, "r", encoding="utf-8") as f:
        return f.read()


#STORE_NAME = "Khana21"

def getVectorStore(client, store_name="Khana21"):

    matches = [
        store for store in client.vector_stores.list().data
        if store.name == store_name
    ]

    if not matches:
        print(f"Vector store '{store_name}' not found")
        return None

    if len(matches) > 1:
        print(
            f"WARNING: {len(matches)} vector stores named "
            f"'{store_name}' found. Using the first."
        )

    return matches[0].id

#------------------------------------------------------------------------------------------

def createVectorStore(client,_name,corpus1, corpus2):
    from openai import OpenAI

    #client = OpenAI()

    # Create our permanent Khawna knowledge base
    vector_store = client.vector_stores.create(name=_name)

    VECTOR_STORE_ID = vector_store.id

    print("Vector Store:", VECTOR_STORE_ID)

    # Upload Braha and Harihar
    with open(corpus1, "rb") as f1, \
         open(corpus2, "rb") as f2:

        result = client.vector_stores.file_batches.upload_and_poll(
            vector_store_id = VECTOR_STORE_ID,
            files=[f1, f2]
        )

    print(result)
    return(VECTOR_STORE_ID)
    

                
#------------------------------------------------------------------------------------------

def buildCaseContext(_chart, _navamsa, _dasha):
    CASE_CONTEXT = f"""
    ====================
    RASHI / NATAL CHART
    ====================
    {_chart}

    ====================
    NAVAMSA
    ====================
    {_navamsa}

    ====================
    VIMSHOTTARI DASHA
    ====================
    {_dasha}
    """
    return(CASE_CONTEXT)

#------------------------------------------------------------------------------------------
                
def LLM_Response(client,systemPrompt, caseContext, cQuestion, vsID,_model) :
    # Call to LLM
    response = client.responses.create(
    model=_model,
    instructions=systemPrompt,
    input=f"""
    {caseContext}

    ====================
    QUESTION
    ====================
    {cQuestion}
    """,

        tools=[
            {
                "type": "file_search",
                "vector_store_ids": [vsID]
            }
        ]
    )
    return(response)
    
#------------------------------------------------------------------------------------------

def xprettierPrint(response):

    display(Markdown(response.output_text))

    usage = response.usage

    print("-" * 80)
    print(
        f"Tokens: "
        f"input={usage.input_tokens:,} | "
        f"output={usage.output_tokens:,} | "
        f"total={usage.total_tokens:,}"
    )
    print("-" * 80)
    
def prettierPrint(response, personID=None, title="Horoscope Assessment", createWord=True):
    """Display response in Colab and optionally create a Word report."""

    from IPython.display import display, Markdown

    # Display formatted response
    #display(Markdown(response.output_text))

    # Usage information
    usage = response.usage
    modelName = getattr(response, "model", "Unknown")

    print("\n" + "-" * 80)
    print(f"Model : {modelName}")
    print(f"Tokens: input={usage.input_tokens:,} | "
          f"output={usage.output_tokens:,} | "
          f"total={usage.total_tokens:,}")

    inputDetails = getattr(usage, "input_tokens_details", None)
    if inputDetails:
        cachedTokens = getattr(inputDetails, "cached_tokens", 0)
        if cachedTokens:
            print(f"Cached input tokens: {cachedTokens:,}")

    print("-" * 80)

    # Create Word report
    if createWord and personID:
        return createDocx(response, personID, title)

    if createWord and not personID:
        print("DOCX not created: personID not supplied.")

    return None    
    
#------------------------------------------------------------------------------------------

def showVectorStores(client):
    stores = client.vector_stores.list()

    for store in stores.data:
            print(store.id, store.name)
            
def deleteVectorStores(client):
    stores = client.vector_stores.list()

    for store in stores.data:
        print(store.id, store.name)
        client.vector_stores.delete(vector_store_id=store.id)
        
def showCorpusFiles(client):
    files = client.files.list()

    for f in files.data:
        print(f.id, f.filename)
        
def deleteCorpusFiles(client):
    files = client.files.list()

    for f in files.data:
        print(f.id, f.filename)
        client.files.delete(f.id)

    print("Corpus files deleted")
        

#------------------------------------------------------------------------------------------
# ============================================================
# DOCX HELPER FUNCTIONS
# ============================================================

def _addFormattedText(paragraph, text):
    """Convert simple Markdown bold/italic into Word formatting."""

    import re

    pattern = r'(\*\*.*?\*\*|\*.*?\*)'
    parts = re.split(pattern, text)

    for part in parts:
        if not part:
            continue

        if part.startswith("**") and part.endswith("**"):
            run = paragraph.add_run(part[2:-2])
            run.bold = True

        elif part.startswith("*") and part.endswith("*"):
            run = paragraph.add_run(part[1:-1])
            run.italic = True

        else:
            paragraph.add_run(part)


def _addPageNumber(paragraph):
    """Insert an automatic Word PAGE field."""

    from docx.oxml import OxmlElement
    from docx.oxml.ns import qn

    run = paragraph.add_run()

    begin = OxmlElement("w:fldChar")
    begin.set(qn("w:fldCharType"), "begin")

    instr = OxmlElement("w:instrText")
    instr.set(qn("xml:space"), "preserve")
    instr.text = "PAGE"

    end = OxmlElement("w:fldChar")
    end.set(qn("w:fldCharType"), "end")

    run._r.append(begin)
    run._r.append(instr)
    run._r.append(end)

#------------------------------------------------------------------------------------------
# ============================================================
# DOCX CREATOR
# ============================================================

def createDocx(
    response,
    personID,
    title="Horoscope Assessment",
    outputDir="/content"
):
    """
    Create a formatted Khana21 Word report.

    Filename:
        K21<PersonID>_HHMMSS.docx

    Example:
        K21TG_134527.docx

    Returns:
        Full path of generated DOCX file.
    """

    import os
    import re

    from datetime import datetime
    from docx import Document
    from docx.shared import Inches, Pt
    from docx.enum.text import WD_ALIGN_PARAGRAPH

    # ---------------------------------------------------------
    # FILE NAME
    # ---------------------------------------------------------

    now = datetime.now()

    filename = (
        f"K21{personID}_{now.strftime('%H%M%S')}.docx"
    )

    filepath = os.path.join(outputDir, filename)

    # ---------------------------------------------------------
    # CREATE DOCUMENT
    # ---------------------------------------------------------

    doc = Document()

    section = doc.sections[0]

    section.top_margin = Inches(0.75)
    section.bottom_margin = Inches(0.75)
    section.left_margin = Inches(0.85)
    section.right_margin = Inches(0.85)

    # ---------------------------------------------------------
    # NORMAL TEXT STYLE
    # ---------------------------------------------------------

    normal = doc.styles["Normal"]

    normal.font.name = "Aptos"
    normal.font.size = Pt(10.5)

    normal.paragraph_format.space_after = Pt(6)
    normal.paragraph_format.line_spacing = 1.08

    # ---------------------------------------------------------
    # HEADING STYLES
    # ---------------------------------------------------------

    headingStyles = [
        ("Title", 20),
        ("Heading 1", 16),
        ("Heading 2", 13),
        ("Heading 3", 11)
    ]

    for styleName, fontSize in headingStyles:

        style = doc.styles[styleName]

        style.font.name = "Aptos Display"
        style.font.size = Pt(fontSize)
        style.font.bold = True

    # ---------------------------------------------------------
    # HEADER
    # ---------------------------------------------------------

    header = section.header

    p = header.paragraphs[0]
    p.alignment = WD_ALIGN_PARAGRAPH.LEFT

    run = p.add_run(
        "卐   PARASHAR21 / KHANA21   卐"
    )

    run.font.name = "Aptos"
    run.font.size = Pt(9)
    run.bold = True

    # ---------------------------------------------------------
    # FOOTER
    # ---------------------------------------------------------

    footer = section.footer

    p = footer.paragraphs[0]
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER

    generated = now.strftime(
        "%d %b %Y  %H:%M:%S"
    )

    run = p.add_run(
        f"Person ID: {personID}   |   "
        f"Generated: {generated}   |   "
        f"Page "
    )

    run.font.name = "Aptos"
    run.font.size = Pt(8)

    _addPageNumber(p)

    # ---------------------------------------------------------
    # DOCUMENT TITLE
    # ---------------------------------------------------------

    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.LEFT

    run = p.add_run(f"Jyotish Analysis   |   Person ID: {personID}")
    run.bold = True
    run.font.name = "Aptos Display"
    run.font.size = Pt(16)

    doc.add_paragraph()

    # ---------------------------------------------------------
    # CONVERT RESPONSE MARKDOWN TO WORD
    # ---------------------------------------------------------

    markdownText = response.output_text

    for rawLine in markdownText.splitlines():

        line = rawLine.strip()

        # Blank line
        if not line:
            continue

        # Heading 1
        if line.startswith("# "):

            doc.add_heading(
                line[2:].strip(),
                level=1
            )

        # Heading 2
        elif line.startswith("## "):

            doc.add_heading(
                line[3:].strip(),
                level=2
            )

        # Heading 3
        elif line.startswith("### "):

            doc.add_heading(
                line[4:].strip(),
                level=3
            )

        # Block quote
        elif line.startswith(">"):

            p = doc.add_paragraph()

            p.paragraph_format.left_indent = (
                Inches(0.3)
            )

            run = p.add_run(
                line[1:].strip()
            )

            run.italic = True

        # Bullet
        elif re.match(
            r"^[-*]\s+",
            line
        ):

            text = re.sub(
                r"^[-*]\s+",
                "",
                line
            )

            p = doc.add_paragraph(
                style="List Bullet"
            )

            _addFormattedText(
                p,
                text
            )

        # Numbered list
        elif re.match(
            r"^\d+\.\s+",
            line
        ):

            text = re.sub(
                r"^\d+\.\s+",
                "",
                line
            )

            p = doc.add_paragraph(
                style="List Number"
            )

            _addFormattedText(
                p,
                text
            )

        # Ignore Markdown horizontal rules
        elif re.match(
            r"^-{3,}$",
            line
        ):

            continue

        # Ordinary paragraph
        else:

            p = doc.add_paragraph()

            _addFormattedText(
                p,
                line
            )

    # ---------------------------------------------------------
    # END NOTE
    # ---------------------------------------------------------

    doc.add_paragraph()

    p = doc.add_paragraph()

    p.paragraph_format.space_before = Pt(12)

    run = p.add_run(
        "This interpretation was generated by Khana21 "
        "using computational chart data from Parashar21 "
        "and the authorised Jyotisha reference corpus."
    )

    run.italic = True
    run.font.size = Pt(8)

    # ---------------------------------------------------------
    # DOCUMENT METADATA
    # ---------------------------------------------------------

    doc.core_properties.title = title

    doc.core_properties.subject = (
        "Khana21 Jyotisha Analysis"
    )

    doc.core_properties.author = (
        "Parashar21 / Khana21"
    )

    # Keep model information in metadata
    modelName = getattr(
        response,
        "model",
        "Unknown"
    )

    doc.core_properties.keywords = (
        f"Khana21, Parashar21, "
        f"{personID}, {modelName}"
    )

    # ---------------------------------------------------------
    # SAVE
    # ---------------------------------------------------------

    doc.save(filepath)

    print(
        f"Word report created: {filepath}"
    )

    return filepath

#------------------------------------------------------------------------------------------

    
def TestRetrieval(client, vsID, cquery):
    # Pure retrieval test — NO LLM

    results = client.vector_stores.search(
        #vector_store_id="vs_6ab4bd1cfbe081919a3876771cfd3271",
        vector_store_id = vsID,
        query=cquery
    )

    for i, item in enumerate(results.data, 1):
        print(f"\n{'='*70}")
        print(f"RESULT {i}")
        print(f"File:  {item.filename}")
        print(f"Score: {item.score:.4f}")

        for content in item.content:
            if content.type == "text":
                print(content.text)

