# Copyright (c) 2022, Prithwis Mukerjee
# All rights reserved.
#
# This source code is licensed under the GNU GPL v3.0-style license found in the
# LICENSE file in the root directory of this source tree.

# --------------------------------------------------
# P21LLM02.py
# Refactored LLM Input Generator
# This code generated by ChatGPT based on MS DOC report writer code
# --------------------------------------------------

import os
from datetime import datetime

import p21


# --------------------------------------------------
# Global Name Dictionaries
# --------------------------------------------------

GRAHA_NAME = {
    "La": "Lagna",
    "Su": "Sun",
    "Mo": "Moon",
    "Ma": "Mars",
    "Me": "Mercury",
    "Ju": "Jupiter",
    "Ve": "Venus",
    "Sa": "Saturn",
    "Ra": "Rahu",
    "Ke": "Ketu"
}


RASHI_NAME = {
    1: "Aries",
    2: "Taurus",
    3: "Gemini",
    4: "Cancer",
    5: "Leo",
    6: "Virgo",
    7: "Libra",
    8: "Scorpio",
    9: "Sagittarius",
    10: "Capricorn",
    11: "Aquarius",
    12: "Pisces"
}


GENDER_NAME = {
    "M": "Male",
    "F": "Female"
}


GRAHA_ORDER = [
    "La",
    "Su",
    "Mo",
    "Ma",
    "Me",
    "Ju",
    "Ve",
    "Sa",
    "Ra",
    "Ke"
]


# --------------------------------------------------
# Utility Functions
# --------------------------------------------------

def GName(g):
    return GRAHA_NAME.get(g, g)


def GList(lst):
    return [GName(x) for x in lst]


def RName(r):
    return RASHI_NAME.get(int(r), r)


def GetGender():

    gender = "Unknown"

    if hasattr(p21, "ck") and len(p21.ck) > 0:
        gender = GENDER_NAME.get(
            p21.ck[0].upper(),
            p21.ck[0]
        )

    return gender


# Convention:
# p21.pName == p21.gName  -> Gochar analysis
# p21.pName != p21.gName  -> Natal analysis

def GetAnalysisMode(filename):

    if p21.AnalysisType == 'Navamsa':
        filename = 'Navamsa'+filename
        
    if p21.pName == p21.gName:
        analysisMode = "Gochar"
        filename = "Gochar_" + filename
    else:
        analysisMode = "Natal"

    return analysisMode, filename

# --------------------------------------------------
# Header Generator
# --------------------------------------------------


def AddHeader(lines, analysisMode, title):

    def add(text=""):
        lines.append(text)

    add(title)
    add("=" * len(title))
    add("")

    add("Analysis : " + analysisMode)
    add("Chart Type : " + str(p21.AnalysisType))
    add("Gender : " + GetGender())

    if hasattr(p21, "pTags"):
        add("Tags : " + str(p21.pTags))

    add("")

# --------------------------------------------------
# House Lordship Generator
# --------------------------------------------------

def AddHouseLordship(lines):

    def add(text=""):
        lines.append(text)

    add("HOUSE LORDSHIP")
    add("--------------")

    for house in range(1, len(p21.Lord)):

        lord = p21.Lord[house]

        add(
            f"House {house} lord is {GName(lord)}"
        )

    add("")
	
# --------------------------------------------------
# Planetary Information Generator
# --------------------------------------------------

def AddPlanetaryInformation(lines):

    def add(text=""):
        lines.append(text)

    add("PLANETARY INFORMATION")
    add("---------------------")

    for graha in GRAHA_ORDER:

        if graha not in p21.GrahaBhava:
            continue

        add("")
        add(GName(graha) + ":")

        add(
            f"- Occupies Bhava {p21.GrahaBhava[graha]}"
        )

        if graha in p21.GRashiN:
            add(
                f"- Located in Rashi {RName(p21.GRashiN[graha])}"
            )

        if graha in p21.GrahaLordBhav:
            add(
                f"- Lord of Bhavas {p21.GrahaLordBhav[graha]}"
            )

        if p21.exaltG.get(graha, False):
            add("- Exalted")

        if p21.debilG.get(graha, False):
            add("- Debilitated")

        if p21.ownHouseG.get(graha, False):
            add("- In own house")

        if p21.inFriendG.get(graha, False):
            add("- In friendly house")

        if p21.inEnemyG.get(graha, False):
            add("- In enemy house")

        if p21.beneficG.get(graha, False):
            add("- Functional benefic")

        if p21.maleficG.get(graha, False):
            add("- Functional malefic")

        if p21.GRet.get(graha, False):
            add("- Retrograde")

        if graha in p21.GLon:
            add(
                f"- Absolute celestial longitude {p21.GLon[graha]} degrees"
            )

    add("")

# --------------------------------------------------
# Planetary Aspects
# --------------------------------------------------

def AddPlanetaryAspects(lines):

    def add(text=""):
        lines.append(text)

    add("PLANETARY ASPECTS")
    add("-----------------")

    for graha, targets in p21.GAspects2.items():

        add(
            f"{GName(graha)} aspects {GList(targets)}"
        )

    add("")

# --------------------------------------------------
# Planets Aspected By
# --------------------------------------------------

def AddPlanetsAspectedBy(lines):

    def add(text=""):
        lines.append(text)

    add("PLANETS ASPECTED BY")
    add("--------------------")

    for graha, sources in p21.GAspectedBy2.items():

        add(
            f"{GName(graha)} is aspected by {GList(sources)}"
        )


    add("")

# --------------------------------------------------
# Planetary Conjunctions
# --------------------------------------------------

def AddPlanetaryConjunctions(lines):

    def add(text=""):
        lines.append(text)

    add("PLANETARY CONJUNCTIONS")
    add("-----------------------")

    for graha, targets in p21.GConjunctsG2.items():

        add(
            f"{GName(graha)} conjuncts {GList(targets)}"
        )

    add("")

# --------------------------------------------------
# House Lord - Planet Relationships
# --------------------------------------------------

def AddHouseLordRelationships(lines):

    def add(text=""):
        lines.append(text)

    add("HOUSE LORD RELATIONSHIPS")
    add("-------------------------")

    for lord, grahas in p21.BLConjunctsG2.items():

        add(
            f"Lord of Bhava {lord} conjuncts {GList(grahas)}"
        )

    add("")

# --------------------------------------------------
# Lord - Lord Relationships
# --------------------------------------------------

def AddLordLordRelationships(lines):

    def add(text=""):
        lines.append(text)

    add("LORD LORD RELATIONSHIPS")
    add("-----------------------")

    for lord, others in p21.BLConjunctsBL2.items():

        others = [int(x) for x in others]
        add(
            f"Lord of Bhava {lord} connected with Lords {others}"
        )

    add("")
	
# --------------------------------------------------
# Bhava Aspects
# --------------------------------------------------

def AddBhavaAspects(lines):

    def add(text=""):
        lines.append(text)

    add("BHAVA ASPECTS")
    add("--------------")

    for bhav in sorted(p21.BAspectedBy2.keys(), key=int):

        add(
            f"Bhava {bhav} receives aspect from "
            f"{GList(p21.BAspectedBy2[bhav])}"
        )

    add("")

# --------------------------------------------------
# Bhava Aspected By Lords
# --------------------------------------------------

def AddBhavaAspectedByLords(lines):

    def add(text=""):
        lines.append(text)

    add("BHAVA ASPECTED BY LORDS")
    add("------------------------")

    for bhav in sorted(p21.BAspectedByBL2.keys(), key=int):

        add(
            f"Bhava {bhav} receives aspect from Lords "
            f"{p21.BAspectedByBL2[bhav]}"
        )

    add("")

# --------------------------------------------------
# Yogas
# --------------------------------------------------

def AddYogas(lines):

    def add(text=""):
        lines.append(text)

    add("IDENTIFIED YOGAS")
    add("----------------")

    for yoga in p21.yogsFound:

        add(yoga)

    add("")


# --------------------------------------------------
# Vimshottari Dasha
# --------------------------------------------------

def AddDashaFull(lines):

    def add(text=""):
        lines.append(text)

    add("VIMSHOTTARI DASHA")
    add("-----------------")
    add("")

    for maha, mahaData in p21.VimDasha.items():

        add("Mahadasha : " + GName(maha))
        add("Mahadasha Ends : " + mahaData["End"])
        add("")

        for antar, antarData in mahaData.items():

            if isinstance(antarData, dict):

                add("    Antardasha : " + GName(antar))
                add("    Ends : " + antarData["End"])
                add("")

        add("--------------------------------------------------")
        add("")

    add("")

# --------------------------------------------------
# Main LLM Input Generator
# --------------------------------------------------


def R601_GenerateLLMInput05(filename="Chart.txt"):

    lines = []

    analysisMode, filename = GetAnalysisMode(filename)

    AddHeader(
        lines,
        analysisMode,
        "HOROSCOPE DATA FOR JYOTISHA REASONING"
    )

    AddHouseLordship(lines)

    AddPlanetaryInformation(lines)

    AddPlanetaryAspects(lines)

    AddPlanetsAspectedBy(lines)

    AddPlanetaryConjunctions(lines)

    AddHouseLordRelationships(lines)

    AddLordLordRelationships(lines)

    AddBhavaAspects(lines)

    AddBhavaAspectedByLords(lines)

    #AddYogas(lines)

    #AddDasha(lines)

    with open(
        filename,
        "w",
        encoding="utf-8"
    ) as f:

        f.write(
            "\n".join(lines)
        )
# --------------------------------------------------------------------------------------------
def R602_GenerateLLMInput01(filename="Dasha.txt"):

    lines = []

    analysisMode, filename = GetAnalysisMode(filename)

    AddHeader(
        lines,
        analysisMode,
        "VIMSHOTTARI DASHA FOR JYOTISHA REASONING"
    )


    #AddDasha(lines)
    AddDashaFull(lines)

    with open(
        filename,
        "w",
        encoding="utf-8"
    ) as f:

        f.write(
            "\n".join(lines)
        )
# --------------------------------------------------------------------------------------------